### ISSUE TITLE
InvalidKeyException when setting `encrypt-data = true`

### ISSUE THREAD

**Issue by mlangc** [softwaremill/akka-http-session#9]
I get

```
java.security.InvalidKeyException: Invalid AES key length: 18 bytes
    at com.sun.crypto.provider.AESCipher.engineGetKeySize(AESCipher.java:495)
    at javax.crypto.Cipher.passCryptoPermCheck(Cipher.java:1067)
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1025)
    at javax.crypto.Cipher.implInit(Cipher.java:801)
    at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
    at javax.crypto.Cipher.init(Cipher.java:1249)
    at javax.crypto.Cipher.init(Cipher.java:1186)
    at com.softwaremill.session.Crypto$.encrypt_AES(Crypto.scala:29)
    at com.softwaremill.session.BasicSessionEncoder.encode(SessionEncoder.scala:34)
    at com.softwaremill.session.ClientSessionManager$class.encode(SessionManager.scala:60)
    at com.softwaremill.session.SessionManager$$anon$1.encode(SessionManager.scala:14)
    at com.softwaremill.session.ClientSessionManager$class.createCookie(SessionManager.scala:40)
    at com.softwaremill.session.SessionManager$$anon$1.createCookie(SessionManager.scala:14)
    at com.softwaremill.session.OneOffSessionDirectives$class.setOneOffSession(SessionDirectives.scala:104)
    at com.softwaremill.session.SessionDirectives$.setOneOffSession(SessionDirectives.scala:85)
    at com.softwaremill.session.SessionDirectives$class.setSession(SessionDirectives.scala:20)
    at com.softwaremill.session.SessionDirectives$.setSession(SessionDirectives.scala:85)
```

when setting `encrypt-data = true`. Without encryption, the library works fine. I'm using

```
"com.softwaremill.akka-http-session" %% "core" % "0.2.4"
```

with Scala-2.11.8.

**Comment by adamw** [comment]
Can you try `0.2.5-SNAPSHOT`? The secret was incorrectly shortened to 16 bytes, things broke when a character was multiple-byte (as I suppose is the case with your secret)

**Comment by mlangc** [comment]
Upgrading to `0.2.5-SNAPSHOT` does indeed solve my problem, thanks!

**Comment by adamw** [comment]
Great, 0.2.5 should be in central soon
